const NOTIFICATION = {
	RESET_PASSWORD: "RESET_PASSWORD",
	VERIFY_WORKER: "VERIFY_WORKER",
	VERIFIED_WORKER: "VERIFIED_WORKER",
	PLACED_ORDER: "PLACED_ORDER",
	CANCEL_ORDER: "CANCEL_ORDER",
	DISPATCHED_ORDER: "DISPATCHED_ORDER",
	DELIVERED_ORDER: "DELIVERED_ORDER",
	REQUEST_ACCEPTED: "REQUEST_ACCEPTED",
	REQUEST_REJECTED: "REQUEST_REJECTED",
	LEFT_SHOP: "LEFT_SHOP",
	REMOVED_FROM_SHOP: "REMOVED_FROM_SHOP",
	REMINDER: "REMINDER",
};

module.exports = NOTIFICATION;
