const RESPONSE = {
	FOUND: "FOUND",
	NOT_FOUND: "NOT_FOUND",
	CREATED: "CREATED",
	UPDATED: "UPDATED",
	DELETED: "DELETED",
	NOT_AUTHORIZED: "NOT_AUTHORIZED",
	SUCCESS: "SUCCESS",
	FAILURE: "FAILURE",
	ALREADY_EXISTS: "ALREADY_EXISTS",
	INVALID_CONTACT_NUMBER: "INVALID_CONTACT_NUMBER",
	INVALID_PASSWORD: "INVALID_PASSWORD",
};

module.exports = RESPONSE;
