const SERVICE_CATEGORY = {
	BATHROOM: "BATHROOM",
	GROUND: "GROUND",
	KITCHEN: "KITCHEN",
	ROOM: "ROOM",
	VEHICLE: "VEHICLE",
	SOFA_CARPET: "SOFA_CARPET",
	FULL_HOUSE: "FULL_HOUSE",
};

module.exports = SERVICE_CATEGORY;
